-- AlterTable
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "inAppNotificationsEnabled" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "emailNotificationsEnabled" BOOLEAN NOT NULL DEFAULT true;
