ALTER TABLE "EmployeeTask" ADD COLUMN IF NOT EXISTS "delayedAt" TIMESTAMP(3);
ALTER TABLE "EmployeeTask" ADD COLUMN IF NOT EXISTS "lateReason" TEXT;
ALTER TABLE "EmployeeTask" ADD COLUMN IF NOT EXISTS "activeWorkMs" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "EmployeeTask" ADD COLUMN IF NOT EXISTS "segmentStartedAt" TIMESTAMP(3);
